name: webapp_jupyter
channels:
- conda-forge
- anaconda
dependencies:
- anaconda::python=3.6.8
- conda-forge::pandas=1.0.1
- conda-forge::matplotlib=3.1.3
- conda-forge::scikit-learn=0.22.1
- conda-forge::ipympl=0.4.1
- conda-forge::ipython=7.12.0
- conda-forge::notebook=6.0.3
- conda-forge::widgetsnbextension=3.5.1
- conda-forge::ipywidgets=7.5.1
- conda-forge::voila=0.1.20
- conda-forge::git=2.24.0
- conda-forge::rise=5.6.0